### ISSUE TITLE
loophole exits exceptionaly with: "The device has no langid"

### ISSUE THREAD

**Issue by kleewho** [rsc-dev/loophole#4]
I have m400 connected to usb and when trying to list devices using loophole I get this:

```
loophole(no device)>list
Traceback (most recent call last):
  File "__main__.py", line 241, in <module>
    main()
  File "__main__.py", line 234, in main
    cli.cmdloop(__INTRO.format(__version__))
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "__main__.py", line 74, in do_list
    info = Device.get_info(dev)
  File "/home/lklich/Projects/loophole/loophole/polar/__init__.py", line 549, in get_info
    return usb.get_info(usb_device)
  File "/home/lklich/Projects/loophole/loophole/polar/__init__.py", line 472, in get_info
    return self.usb.get_info(usb_device)
  File "/home/lklich/Projects/loophole/loophole/polar/__init__.py", line 370, in get_info
    info['manufacturer'] = self.usb.util.get_string(usb_device, usb_device.iManufacturer)
  File "/usr/local/lib/python2.7/dist-packages/usb/util.py", line 314, in get_string
    raise ValueError("The device has no langid")
ValueError: The device has no langid
```

My lsusb (if needed):

```
➜  loophole git:(master) lsusb                                                                                                                                                                git:(master|) 
Bus 001 Device 004: ID 0a5c:5800 Broadcom Corp. BCM5880 Secure Applications Processor
Bus 001 Device 003: ID 8087:07dc Intel Corp. 
Bus 001 Device 002: ID 8087:8000 Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 002: ID 1bcf:2985 Sunplus Innovation Technology Inc. Laptop Integrated Webcam HD
Bus 002 Device 003: ID 0da4:0008 Polar Electro Oy Loop
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

I'm using ubuntu 16.04 with kernel 4.4

**Comment by klaus7** [comment]
Same problem here on Ubuntu 14.04
`Bus 003 Device 007: ID 0da4:0008 Polar Electro Oy Loop`

```
loophole(no device)>list
Traceback (most recent call last):
  File "__main__.py", line 241, in <module>
    main()
  File "__main__.py", line 234, in main
    cli.cmdloop(__INTRO.format(__version__))
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "__main__.py", line 74, in do_list
    info = Device.get_info(dev)
  File "/home/klaus/git/loophole/loophole/polar/__init__.py", line 549, in get_info
    return usb.get_info(usb_device)
  File "/home/klaus/git/loophole/loophole/polar/__init__.py", line 472, in get_info
    return self.usb.get_info(usb_device)
  File "/home/klaus/git/loophole/loophole/polar/__init__.py", line 370, in get_info
    info['manufacturer'] = self.usb.util.get_string(usb_device, usb_device.iManufacturer)
  File "/usr/local/lib/python2.7/dist-packages/usb/util.py", line 314, in get_string
    raise ValueError("The device has no langid")
ValueError: The device has no langid
```

**Comment by balbinot** [comment]
Hi,

in my case was lack of permission on USB devices on linux. I got the following message when debugging the code

```
ipdb> print self.usb.util.get_langids(usb_device)
*** USBError: [Errno 13] Access denied (insufficient permissions)
```

To check if that is the same problem for you try running as root. If it works add yourself to the dialout group on /etc/group

Didn't check this last part works, but I am running as root for now.

Hope this helps!
